version: '3'

services:
  db: 
    image: postgres
  backend:
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile
    command: pipenv shell python /app/run.py
    ports:
      - "5000:5000"
    depends_on:
      - db