version: '2'
services:
  nginx:
    image: 'jwilder/nginx-proxy'
    restart: always
    networks:
      - fjcamillo
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  fjcamillo:
