version: '3'

services:
  db: 
    image: postgres
  backend:
    build: 
      context: ./
      dockerfile: ../backend/dev.Dockerfile
    command: pipenv run python /app/run.py --host=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - ../backend/:/app